export interface RawTheme {
  level: number;
  difficulty: string;
  tier: 'beginner' | 'intermediate' | 'advanced' | 'expert' | 'master';
  gridSize: number;
  wordCount: number;
  theme: string;
  isMilestone: boolean;
  milestoneReward?: {
    title: string;
    badgeId: string;
    badgeName: string;
    badgeIcon: string;
    bonusCoins: number;
    description: string;
  };
  words: { word: string; clue: string }[];
}

export const themesData: RawTheme[] = [
  // 1: Basic everyday words
  {
    level: 1,
    difficulty: '⭐',
    tier: 'beginner',
    gridSize: 5,
    wordCount: 5,
    theme: 'Basic everyday words',
    isMilestone: false,
    words: [
      { word: 'HOME', clue: 'Where one resides; family base' },
      { word: 'BOOK', clue: 'Bound pages of a story' },
      { word: 'DOOR', clue: 'Entryway to a room' },
      { word: 'ROOM', clue: 'Enclosed space in a building' },
      { word: 'ROOF', clue: 'Top covering of a house' },
      { word: 'BED', clue: 'Cozy furniture for sleeping' },
      { word: 'DESK', clue: 'Table used for writing' },
      { word: 'LAMP', clue: 'Source of electric light' },
      { word: 'KEY', clue: 'Tool used to open locks' },
      { word: 'CUP', clue: 'Small drinking container' },
      { word: 'TEA', clue: 'Brewed hot herbal beverage' },
      { word: 'POT', clue: 'Deep cooking vessel' },
      { word: 'PAN', clue: 'Shallow skillet for frying' },
      { word: 'RUG', clue: 'Soft carpet on the floor' },
      { word: 'PEN', clue: 'Instrument using liquid ink' },
    ],
  },
  // 2: Animals
  {
    level: 2,
    difficulty: '⭐',
    tier: 'beginner',
    gridSize: 5,
    wordCount: 5,
    theme: 'Animals',
    isMilestone: false,
    words: [
      { word: 'CAT', clue: 'Feline pet that purrs' },
      { word: 'DOG', clue: 'Canine friend that barks' },
      { word: 'LION', clue: 'Majestic king of the jungle' },
      { word: 'BEAR', clue: 'Big furry forest creature' },
      { word: 'WOLF', clue: 'Wild howling canine pack animal' },
      { word: 'FROG', clue: 'Amphibian that hops and croaks' },
      { word: 'BIRD', clue: 'Feathered flying creature' },
      { word: 'DEER', clue: 'Graceful antlered herbivore' },
      { word: 'HARE', clue: 'Fast long-eared mammal' },
      { word: 'FOX', clue: 'Cunning reddish woodland creature' },
      { word: 'OWL', clue: 'Wise nocturnal bird with keen eyes' },
      { word: 'BAT', clue: 'Flying nocturnal mammal' },
      { word: 'PIG', clue: 'Pink farm animal that oinks' },
      { word: 'COW', clue: 'Bovine farm animal giving milk' },
      { word: 'BEE', clue: 'Buzzing insect that makes honey' },
    ],
  },
  // 3: Food
  {
    level: 3,
    difficulty: '⭐',
    tier: 'beginner',
    gridSize: 5,
    wordCount: 6,
    theme: 'Food',
    isMilestone: false,
    words: [
      { word: 'BREAD', clue: 'Baked wheat loaf staple' },
      { word: 'APPLE', clue: 'Crisp red or green orchard fruit' },
      { word: 'PEAR', clue: 'Sweet teardrop-shaped fruit' },
      { word: 'EGG', clue: 'Breakfast oval with a yolk' },
      { word: 'MEAT', clue: 'Protein food from livestock' },
      { word: 'SOUP', clue: 'Warm broth with vegetables' },
      { word: 'RICE', clue: 'Small grains eaten worldwide' },
      { word: 'BEAN', clue: 'Legume seed rich in protein' },
      { word: 'CAKE', clue: 'Sweet baked celebration dessert' },
      { word: 'PIE', clue: 'Baked dish with fruit in crust' },
      { word: 'JAM', clue: 'Sweet fruit spread for toast' },
      { word: 'TEA', clue: 'Brewed hot infusion' },
      { word: 'NUT', clue: 'Hard-shelled dry kernel' },
      { word: 'OAT', clue: 'Cereal grain used in porridge' },
      { word: 'PEA', clue: 'Small green round legume' },
    ],
  },
  // 4: Colors & objects
  {
    level: 4,
    difficulty: '⭐',
    tier: 'beginner',
    gridSize: 5,
    wordCount: 6,
    theme: 'Colors & objects',
    isMilestone: false,
    words: [
      { word: 'RED', clue: 'Color of fire engines and ripe cherries' },
      { word: 'BLUE', clue: 'Color of the clear daytime sky' },
      { word: 'PINK', clue: 'Pale hue of blush roses' },
      { word: 'GOLD', clue: 'Precious yellow metallic luster' },
      { word: 'GRAY', clue: 'Neutral shade between black and white' },
      { word: 'BALL', clue: 'Round toy used in many games' },
      { word: 'RING', clue: 'Circular jewelry worn on a finger' },
      { word: 'BELL', clue: 'Metallic instrument that chimes' },
      { word: 'ROPE', clue: 'Thick cord twisted from strands' },
      { word: 'VASE', clue: 'Decorative jar holding flowers' },
      { word: 'CLOCK', clue: 'Device displaying hours and minutes' },
      { word: 'BOX', clue: 'Cardboard or wood container' },
      { word: 'CAP', clue: 'Visored headwear for sun shade' },
      { word: 'BAG', clue: 'Pouch used for carrying groceries' },
      { word: 'PEN', clue: 'Writing tool with indelible ink' },
      { word: 'GEM', clue: 'Sparkling precious gemstone' },
      { word: 'PIN', clue: 'Sharp pointed metal fastener' },
      { word: 'HAT', clue: 'Headwear shielding from the sun' },
      { word: 'CUP', clue: 'Small vessel for hot tea' },
      { word: 'MUG', clue: 'Sturdy ceramic cup with handle' },
      { word: 'JAR', clue: 'Glass container with a lid' },
      { word: 'KEY', clue: 'Metal instrument for unlocking' },
      { word: 'FAN', clue: 'Device for creating a cool breeze' },
      { word: 'RUG', clue: 'Woven floor covering' },
      { word: 'BOW', clue: 'Ribbon tied in a decorative loop' },
      { word: 'TIN', clue: 'Silvery metal container' },
      { word: 'NET', clue: 'Mesh used for catching or sports' },
      { word: 'POT', clue: 'Cooking container for stews' },
      { word: 'PAN', clue: 'Flat frying skillet' },
      { word: 'TOP', clue: 'Spinning toy balanced on a point' },
    ],
  },
  // 5: Family & home (Milestone 1)
  {
    level: 5,
    difficulty: '⭐',
    tier: 'beginner',
    gridSize: 6,
    wordCount: 7,
    theme: 'Family & home',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 1 Reached!',
      badgeId: 'home_builder',
      badgeName: 'Home Builder',
      badgeIcon: 'Home',
      bonusCoins: 50,
      description: 'You completed your first milestone challenge! Home & Family unlocked.',
    },
    words: [
      { word: 'FATHER', clue: 'Male parent and role model' },
      { word: 'MOTHER', clue: 'Female parent full of care' },
      { word: 'SISTER', clue: 'Female sibling in the family' },
      { word: 'COUSIN', clue: 'Child of your aunt or uncle' },
      { word: 'FAMILY', clue: 'Loved ones related by blood or bond' },
      { word: 'GARDEN', clue: 'Outdoor area with flowers and lawn' },
      { word: 'ATTIC', clue: 'Space just below the house roof' },
      { word: 'PORCH', clue: 'Covered entrance shelter on a house' },
      { word: 'SOFA', clue: 'Living room couch for lounging' },
      { word: 'DOOR', clue: 'Entryway swing portal' },
      { word: 'ROOF', clue: 'Top protective house covering' },
      { word: 'ROOM', clue: 'Subdivided space inside a home' },
      { word: 'AUNT', clue: 'Sister of your mother or father' },
      { word: 'SON', clue: 'Male offspring' },
      { word: 'MOM', clue: 'Affectionate name for mother' },
      { word: 'DAD', clue: 'Affectionate name for father' },
      { word: 'BED', clue: 'Mattress piece for nighttime rest' },
    ],
  },
  // 6: Nature
  {
    level: 6,
    difficulty: '⭐⭐',
    tier: 'beginner',
    gridSize: 6,
    wordCount: 7,
    theme: 'Nature',
    isMilestone: false,
    words: [
      { word: 'FOREST', clue: 'Dense growth of trees and wilderness' },
      { word: 'STREAM', clue: 'Small narrow flowing river' },
      { word: 'FLOWER', clue: 'Blossoming colorful plant part' },
      { word: 'VALLEY', clue: 'Low land nestled between mountains' },
      { word: 'RIVER', clue: 'Broad flowing waterway to the sea' },
      { word: 'BEACH', clue: 'Sandy coastline touched by waves' },
      { word: 'CLOUD', clue: 'Condensed water vapor in the sky' },
      { word: 'PLANT', clue: 'Living organism producing oxygen' },
      { word: 'TREE', clue: 'Tall perennial woody plant' },
      { word: 'LEAF', clue: 'Green foliage growing on stems' },
      { word: 'RAIN', clue: 'Precipitation watering the earth' },
      { word: 'WIND', clue: 'Movement of air across the land' },
      { word: 'MOON', clue: 'Natural satellite orbiting Earth' },
      { word: 'STAR', clue: 'Luminous celestial sphere of plasma' },
      { word: 'HILL', clue: 'Natural elevation smaller than mountain' },
      { word: 'SUN', clue: 'Central bright star of our system' },
    ],
  },
  // 7: School
  {
    level: 7,
    difficulty: '⭐⭐',
    tier: 'beginner',
    gridSize: 6,
    wordCount: 8,
    theme: 'School',
    isMilestone: false,
    words: [
      { word: 'LESSON', clue: 'Period of learning or instructional period' },
      { word: 'STUDY', clue: 'Devoting time to acquire knowledge' },
      { word: 'LEARN', clue: 'Gain knowledge or understanding' },
      { word: 'RULER', clue: 'Straight strip used to measure distance' },
      { word: 'ERASER', clue: 'Rubber tool for rubbing out pencil marks' },
      { word: 'PENCIL', clue: 'Graphite stick in wooden sheath' },
      { word: 'CLASS', clue: 'Group of pupils meeting together' },
      { word: 'GRADE', clue: 'Evaluation mark or score given for work' },
      { word: 'EXAM', clue: 'Formal test of knowledge' },
      { word: 'BOOK', clue: 'Bound textbook full of information' },
      { word: 'DESK', clue: 'School table where students sit' },
      { word: 'TEST', clue: 'Short quiz assessing comprehension' },
      { word: 'READ', clue: 'Inspect and understand written words' },
      { word: 'MATH', clue: 'Study of numbers, shapes, and formulas' },
      { word: 'ART', clue: 'Creative expression with drawing or paint' },
      { word: 'INK', clue: 'Fluid used for writing and printing' },
      { word: 'PEN', clue: 'Tool filled with ink for handwriting' },
    ],
  },
  // 8: Body & health
  {
    level: 8,
    difficulty: '⭐⭐',
    tier: 'beginner',
    gridSize: 6,
    wordCount: 8,
    theme: 'Body & health',
    isMilestone: false,
    words: [
      { word: 'HEART', clue: 'Vital organ pumping blood continuously' },
      { word: 'BRAIN', clue: 'Center of intellect and nervous system' },
      { word: 'ANKLE', clue: 'Joint connecting foot to lower leg' },
      { word: 'ELBOW', clue: 'Hinge joint halfway down the arm' },
      { word: 'TOOTH', clue: 'Hard enamel structure for chewing' },
      { word: 'WRIST', clue: 'Joint connecting hand to forearm' },
      { word: 'CHEST', clue: 'Upper front trunk of human body' },
      { word: 'PULSE', clue: 'Rhythmical throbbing of the arteries' },
      { word: 'KNEE', clue: 'Leg joint allowing bending and squatting' },
      { word: 'NOSE', clue: 'Facial organ for breathing and scents' },
      { word: 'FOOT', clue: 'Lower extremity used for walking' },
      { word: 'HAND', clue: 'Body part with fingers and thumb' },
      { word: 'BONE', clue: 'Rigid skeletal tissue' },
      { word: 'SKIN', clue: 'Outer protective body covering' },
      { word: 'EAR', clue: 'Sensory organ detecting acoustic waves' },
      { word: 'EYE', clue: 'Organ granting vision and sight' },
      { word: 'ARM', clue: 'Upper limb extending from shoulder' },
    ],
  },
  // 9: Places
  {
    level: 9,
    difficulty: '⭐⭐',
    tier: 'beginner',
    gridSize: 6,
    wordCount: 9,
    theme: 'Places',
    isMilestone: false,
    words: [
      { word: 'MUSEUM', clue: 'Institution housing art, history, or science' },
      { word: 'MARKET', clue: 'Open gathering of merchant stalls' },
      { word: 'HARBOR', clue: 'Sheltered body of water where ships dock' },
      { word: 'ISLAND', clue: 'Land tract completely surrounded by water' },
      { word: 'HOTEL', clue: 'Establishment providing lodging for travelers' },
      { word: 'PLAZA', clue: 'Public open town square' },
      { word: 'BEACH', clue: 'Seashore with sand and pebbles' },
      { word: 'PARK', clue: 'Recreation ground with grass and trees' },
      { word: 'CITY', clue: 'Large populated urban center' },
      { word: 'TOWN', clue: 'Urban settlement smaller than city' },
      { word: 'FARM', clue: 'Land dedicated to growing crops and animals' },
      { word: 'PORT', clue: 'Maritime destination for cargo ships' },
      { word: 'ROAD', clue: 'Paved path for vehicular travel' },
      { word: 'LAKE', clue: 'Inland body of standing fresh water' },
      { word: 'CAFE', clue: 'Cozy spot serving coffee and pastries' },
      { word: 'SHOP', clue: 'Store selling merchandise or services' },
      { word: 'ZOO', clue: 'Park displaying wild animal species' },
      { word: 'SPA', clue: 'Resort offering mineral baths and massages' },
      { word: 'INN', clue: 'Cozy countryside lodging for travelers' },
      { word: 'PUB', clue: 'Tavern serving ales and hearty meals' },
      { word: 'HUT', clue: 'Small simple rustic shelter' },
      { word: 'DEN', clue: 'Cozy private room or animal lair' },
      { word: 'GYM', clue: 'Facility for athletic exercise and weights' },
      { word: 'BAY', clue: 'Broad inlet of the sea curving inland' },
      { word: 'LAB', clue: 'Laboratory room for scientific testing' },
      { word: 'BAR', clue: 'Establishment serving drinks at a counter' },
      { word: 'MALL', clue: 'Enclosed shopping center with diverse stores' },
      { word: 'BANK', clue: 'Financial institution storing money and gold' },
      { word: 'CAMP', clue: 'Outdoor site with tents under the stars' },
      { word: 'PIER', clue: 'Platform projecting out into coastal waters' },
    ],
  },
  // 10: Sports (Milestone 2)
  {
    level: 10,
    difficulty: '⭐⭐',
    tier: 'beginner',
    gridSize: 6,
    wordCount: 9,
    theme: 'Sports',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 2 Reached!',
      badgeId: 'athletic_champion',
      badgeName: 'Athletic Gold',
      badgeIcon: 'Trophy',
      bonusCoins: 75,
      description: 'Ten levels conquered! You unlocked the Sports Champion Milestone.',
    },
    words: [
      { word: 'SOCCER', clue: 'World game with 11 players per team kicking a ball' },
      { word: 'TENNIS', clue: 'Racket duel across a low center net' },
      { word: 'BOXING', clue: 'Combat sport inside a roped ring' },
      { word: 'RUNNER', clue: 'Athlete racing on foot across distances' },
      { word: 'BALL', clue: 'Spherical equipment used in countless sports' },
      { word: 'GOAL', clue: 'Net target where points are scored' },
      { word: 'TEAM', clue: 'Collaborative roster of athletes' },
      { word: 'RACE', clue: 'Speed contest toward a finish line' },
      { word: 'CLUB', clue: 'Shafted implement used to hit golf balls' },
      { word: 'RING', clue: 'Square canvas enclosed by ropes' },
      { word: 'SWIM', clue: 'Propelling through water in lanes' },
      { word: 'JUMP', clue: 'Leaping over hurdles or bar' },
      { word: 'SURF', clue: 'Riding breaking ocean waves on a board' },
      { word: 'SKI', clue: 'Gliding down snowy alpine slopes' },
      { word: 'NET', clue: 'Dividing mesh on tennis or volleyball courts' },
      { word: 'BAT', clue: 'Wooden club used in baseball and cricket' },
      { word: 'CUP', clue: 'Championship trophy awarded to winners' },
      { word: 'WIN', clue: 'Achieve victory in a contest' },
      { word: 'BOW', clue: 'Weapon used in target archery contests' },
      { word: 'ROW', clue: 'Propel a racing scull using oars' },
      { word: 'JOG', clue: 'Run at a steady, gentle pace for fitness' },
      { word: 'MAT', clue: 'Padded floor cushion for wrestling' },
      { word: 'PUCK', clue: 'Vulcanized rubber disc used in ice hockey' },
      { word: 'POOL', clue: 'Deep basin of water for lap swimming' },
      { word: 'FOUL', clue: 'Violation of rules penalizing a player' },
      { word: 'GAME', clue: 'Competitive contest played according to rules' },
    ],
  },
];
