import { RawTheme } from './wordbanks';

export const themes11to25: RawTheme[] = [
  // 11: Travel (7x7, 10 words)
  {
    level: 11,
    difficulty: '⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 10,
    theme: 'Travel',
    isMilestone: false,
    words: [
      { word: 'JOURNEY', clue: 'Act of traveling from one destination to another' },
      { word: 'LUGGAGE', clue: 'Suitcases and bags packed for a trip' },
      { word: 'AIRPORT', clue: 'Complex where airplanes take off and land' },
      { word: 'PASSPORT', clue: 'Official booklet granting international transit' },
      { word: 'CRUISE', clue: 'Pleasure voyage aboard an ocean liner' },
      { word: 'TICKET', clue: 'Document proving payment for admission or transit' },
      { word: 'FLIGHT', clue: 'Trip through the air in an aircraft' },
      { word: 'TRAIN', clue: 'Linked railway carriages on tracks' },
      { word: 'HOTEL', clue: 'Establishment offering rooms for tourists' },
      { word: 'TOUR', clue: 'Guided journey visiting sites of interest' },
      { word: 'MAP', clue: 'Diagram representing physical geography' },
      { word: 'CAR', clue: 'Motor vehicle for road travel' },
      { word: 'BUS', clue: 'Large passenger road vehicle' },
      { word: 'SEA', clue: 'Vast body of salty ocean water' },
      { word: 'TRIP', clue: 'Excursion or brief vacation' },
      { word: 'CAB', clue: 'Taxicab hailed in metropolitan streets' },
    ],
  },
  // 12: Weather (7x7, 10 words)
  {
    level: 12,
    difficulty: '⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 10,
    theme: 'Weather',
    isMilestone: false,
    words: [
      { word: 'THUNDER', clue: 'Booming acoustic rumble caused by lightning' },
      { word: 'TORNADO', clue: 'Violent rotating column of destructive air' },
      { word: 'BREEZE', clue: 'Gentle, refreshing gust of wind' },
      { word: 'STORMY', clue: 'Characterized by severe weather and gale' },
      { word: 'FREEZE', clue: 'Convert liquid water into solid ice' },
      { word: 'DRIZZLE', clue: 'Light precipitation consisting of fine misty droplets' },
      { word: 'SUNNY', clue: 'Brightly lit by radiant sunshine' },
      { word: 'FOGGY', clue: 'Obscured by thick low-lying moisture vapor' },
      { word: 'SNOW', clue: 'Frozen precipitation falling in flakes' },
      { word: 'HAIL', clue: 'Pellets of frozen rain falling from clouds' },
      { word: 'RAIN', clue: 'Condensed atmospheric moisture falling as drops' },
      { word: 'WIND', clue: 'Perceptible natural movement of the atmosphere' },
      { word: 'COLD', clue: 'Low ambient temperature' },
      { word: 'WARM', clue: 'Comfortably moderate heat' },
      { word: 'ICE', clue: 'Frozen crystalline state of water' },
      { word: 'FOG', clue: 'Dense vapor reducing visibility near the ground' },
      { word: 'WET', clue: 'Covered or saturated with water' },
    ],
  },
  // 13: Technology (7x7, 11 words)
  {
    level: 13,
    difficulty: '⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 11,
    theme: 'Technology',
    isMilestone: false,
    words: [
      { word: 'COMPUTER', clue: 'Programmable electronic device for data processing' },
      { word: 'NETWORK', clue: 'Interconnected system of computing devices' },
      { word: 'LAPTOP', clue: 'Portable clamshell personal computer' },
      { word: 'ROUTER', clue: 'Networking device forwarding data packets' },
      { word: 'SCREEN', clue: 'Display surface showing visual output' },
      { word: 'KEYPAD', clue: 'Small numeric input grid on phones' },
      { word: 'SERVER', clue: 'Central computer providing services to clients' },
      { word: 'PHONE', clue: 'Handheld telecommunications device' },
      { word: 'MOUSE', clue: 'Hand-operated pointing peripheral' },
      { word: 'CHIP', clue: 'Miniature integrated electronic circuit' },
      { word: 'CODE', clue: 'Instructions written in programming language' },
      { word: 'DATA', clue: 'Information processed or stored by computer' },
      { word: 'DISK', clue: 'Magnetic storage media platter' },
      { word: 'WIFI', clue: 'Wireless local area networking standard' },
      { word: 'APP', clue: 'Application software designed for tasks' },
      { word: 'NET', clue: 'Short for worldwide digital network' },
      { word: 'WEB', clue: 'World Wide Web system of hyperlinked pages' },
      { word: 'RAM', clue: 'Random access memory in computers' },
      { word: 'BYTE', clue: 'Unit of digital storage formed of 8 bits' },
      { word: 'BIT', clue: 'Single fundamental binary digit 0 or 1' },
      { word: 'BUG', clue: 'Defect or glitch in software code' },
      { word: 'BOT', clue: 'Automated software script executing tasks' },
      { word: 'LINK', clue: 'Hypertext pointer to another web page' },
      { word: 'FILE', clue: 'Named digital collection of stored data' },
      { word: 'ICON', clue: 'Graphic pictogram representing a program' },
      { word: 'LOG', clue: 'Chronological record of computer events' },
    ],
  },
  // 14: Jobs (7x7, 11 words)
  {
    level: 14,
    difficulty: '⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 11,
    theme: 'Jobs',
    isMilestone: false,
    words: [
      { word: 'DOCTOR', clue: 'Qualified medical practitioner treating patients' },
      { word: 'FARMER', clue: 'Person cultivating agricultural crops and livestock' },
      { word: 'WRITER', clue: 'Author crafting literary prose or articles' },
      { word: 'PILOT', clue: 'Licensed aviator navigating an aircraft' },
      { word: 'NURSE', clue: 'Healthcare professional caring for the sick' },
      { word: 'BAKER', clue: 'Tradesperson making bread, cakes, and pastry' },
      { word: 'CHEF', clue: 'Professional head cook in restaurant kitchens' },
      { word: 'CLERK', clue: 'Office worker handling routine records' },
      { word: 'JUDGE', clue: 'Public official presiding over a court of law' },
      { word: 'ACTOR', clue: 'Thespian performing roles in theater and film' },
      { word: 'COACH', clue: 'Trainer instructing an athletic squad' },
      { word: 'TEACH', clue: 'Impart scholastic knowledge to students' },
      { word: 'COP', clue: 'Colloquial term for a police patrol officer' },
      { word: 'VET', clue: 'Animal physician treating pets and fauna' },
      { word: 'LAW', clue: 'Legal field of jurisprudence' },
      { word: 'ART', clue: 'Creative field of painters and sculptors' },
      { word: 'MAID', clue: 'Domestic cleaner maintaining house order' },
      { word: 'BOSS', clue: 'Manager supervising department workers' },
      { word: 'AIDE', clue: 'Assistant helping a senior official' },
      { word: 'GUARD', clue: 'Security officer protecting buildings' },
      { word: 'GUIDE', clue: 'Person leading visitors through monuments' },
      { word: 'HOST', clue: 'Master of ceremonies welcoming guests' },
    ],
  },
  // 15: Everyday life (7x7, 12 words, Milestone 3)
  {
    level: 15,
    difficulty: '⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 12,
    theme: 'Everyday life',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 3 Reached!',
      badgeId: 'master_modernity',
      badgeName: 'Everyday Pathfinder',
      badgeIcon: 'Compass',
      bonusCoins: 100,
      description: 'Level 15 unlocked! You possess great everyday observation skills.',
    },
    words: [
      { word: 'ROUTINE', clue: 'Habitual sequence of daily activities' },
      { word: 'MORNING', clue: 'Early part of day between dawn and noon' },
      { word: 'EVENING', clue: 'Closing period of daylight before nightfall' },
      { word: 'BREAKFAST', clue: 'First nourishing meal eaten after waking' },
      { word: 'KITCHEN', clue: 'Room equipped for culinary meal preparation' },
      { word: 'MARKET', clue: 'Gathering where groceries and goods are purchased' },
      { word: 'DINNER', clue: 'Main substantial evening meal' },
      { word: 'SLEEP', clue: 'Natural state of periodic physical rest' },
      { word: 'SHOWER', clue: 'Bathroom stall for washing under sprayed water' },
      { word: 'CLOCK', clue: 'Timekeeping dial hung upon the wall' },
      { word: 'STREET', clue: 'Public thoroughfare in a city or suburb' },
      { word: 'COFFEE', clue: 'Brewed morning stimulant drink made from beans' },
      { word: 'WALK', clue: 'Stroll on foot for leisure or transit' },
      { word: 'REST', clue: 'Pause from strenuous labor or exertion' },
      { word: 'WORK', clue: 'Employment activity undertaken for livelihood' },
      { word: 'TALK', clue: 'Verbal conversation with neighbors' },
      { word: 'TEA', clue: 'Warm aromatic infusion enjoyed in the afternoon' },
      { word: 'BUS', clue: 'Public transit vehicle on a morning route' },
      { word: 'BED', clue: 'Sanctuary of sheets and pillows for night' },
      { word: 'CUP', clue: 'Ceramic vessel for sipping hot tea' },
      { word: 'PAN', clue: 'Metal cookware on the kitchen stove' },
      { word: 'POT', clue: 'Deep vessel for boiling soups' },
      { word: 'RUG', clue: 'Soft mat on the living room floor' },
      { word: 'KEY', clue: 'Metal tool that locks the front door' },
      { word: 'BAG', clue: 'Sack carrying groceries home' },
      { word: 'BOX', clue: 'Carton holding household items' },
      { word: 'SUN', clue: 'Morning light shining through curtains' },
      { word: 'DOG', clue: 'Loyal canine greeting you at the door' },
      { word: 'CAT', clue: 'Feline companion purring on the sofa' },
    ],
  },
  // 16: Animals — harder (7x7, 12 words)
  {
    level: 16,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 12,
    theme: 'Animals — harder',
    isMilestone: false,
    words: [
      { word: 'DOLPHIN', clue: 'Highly intelligent marine mammal using echolocation' },
      { word: 'CHEETAH', clue: 'Fastest land mammal famous for black tear marks' },
      { word: 'GIRAFFE', clue: 'Tallest terrestrial herbivore with long neck' },
      { word: 'BADGER', clue: 'Burrowing carnivore with distinctive striped head' },
      { word: 'FALCON', clue: 'Fast diving raptor bird with hooked beak' },
      { word: 'WALRUS', clue: 'Arctic marine mammal possessing long ivory tusks' },
      { word: 'JAGUAR', clue: 'Powerful spotted feline native to the Americas' },
      { word: 'OTTER', clue: 'Playful semi-aquatic mammal floating on back' },
      { word: 'BEAVER', clue: 'Rodent known for engineering natural timber dams' },
      { word: 'HYENA', clue: 'Spotted African carnivore known for cackling vocalization' },
      { word: 'EAGLE', clue: 'Magnificent bird of prey symbolic of freedom' },
      { word: 'VIPER', clue: 'Venomous snake with hinged fangs' },
      { word: 'RHINO', clue: 'Massive thick-skinned mammal bearing horn on snout' },
      { word: 'MOOSE', clue: 'Largest species of the deer family with broad antlers' },
      { word: 'SLOTH', clue: 'Tree-dwelling slow mammal of South America' },
      { word: 'PUMA', clue: 'Large solitary American wild cat; cougar' },
      { word: 'FOX', clue: 'Bushy-tailed vulpine scavenger' },
      { word: 'APE', clue: 'Tailless primate closely related to humans' },
      { word: 'ELK', clue: 'Large deer native to North American woodlands' },
    ],
  },
  // 17: Food — harder (7x7, 13 words)
  {
    level: 17,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 7,
    wordCount: 13,
    theme: 'Food — harder',
    isMilestone: false,
    words: [
      { word: 'AVOCADO', clue: 'Creamy green pear-shaped fruit high in healthy fats' },
      { word: 'VANILLA', clue: 'Aromatic flavoring derived from cured orchid pods' },
      { word: 'PAPRIKA', clue: 'Ground sweet red spice made from dried bell peppers' },
      { word: 'SAFFRON', clue: 'Precious crimson stigmas adding golden hue to rice' },
      { word: 'RISOTTO', clue: 'Creamy northern Italian arborio rice specialty' },
      { word: 'SPINACH', clue: 'Nutrient-rich leafy dark green vegetable' },
      { word: 'LASAGNA', clue: 'Baked pasta dish layered with ricotta and ragù' },
      { word: 'ALMOND', clue: 'Oval edible nut used to produce marzipan' },
      { word: 'GARLIC', clue: 'Pungent allium bulb divided into cloves' },
      { word: 'GINGER', clue: 'Zesty underground rhizome used in curries' },
      { word: 'OLIVE', clue: 'Small savory fruit pressed for rich cooking oil' },
      { word: 'BASIL', clue: 'Fragrant green herb essential for genovese pesto' },
      { word: 'THYME', clue: 'Woody aromatic herb with tiny earthy leaves' },
      { word: 'CREAM', clue: 'Fat-rich butterfat portion skimmed from milk' },
      { word: 'HONEY', clue: 'Viscous golden nectar manufactured by bees' },
      { word: 'CURRY', clue: 'Spiced aromatic stew sauce with turmeric' },
      { word: 'BEEF', clue: 'Culinary meat obtained from mature cattle' },
      { word: 'PORK', clue: 'Culinary meat yielded from swine' },
      { word: 'FIG', clue: 'Soft tear-shaped sweet fruit with tiny crunchy seeds' },
      { word: 'EGG', clue: 'Culinary staple used in baking custard' },
    ],
  },
  // 18: Geography (8x8, 13 words)
  {
    level: 18,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 13,
    theme: 'Geography',
    isMilestone: false,
    words: [
      { word: 'GLACIER', clue: 'Slow-moving persistent mass of dense alpine ice' },
      { word: 'VOLCANO', clue: 'Rupture in Earth crust allowing lava and ash escape' },
      { word: 'PLATEAU', clue: 'Area of elevated flat land with steep edges' },
      { word: 'CANYON', clue: 'Deep gorge carved through rock by a river' },
      { word: 'ISLAND', clue: 'Sub-continental landmass encircled by waters' },
      { word: 'DESERT', clue: 'Arid barren landscape with minimal annual rainfall' },
      { word: 'VALLEY', clue: 'Elongated low terrain between hills or ridges' },
      { word: 'LAGOON', clue: 'Shallow coastal pool separated from the ocean by reef' },
      { word: 'RIVER', clue: 'Large natural flow of water into sea or lake' },
      { word: 'OCEAN', clue: 'Vast continuous expanse of saline water' },
      { word: 'COAST', clue: 'Land bordering an expanse of sea or ocean' },
      { word: 'DELTA', clue: 'Wetland formed where rivers empty into oceans' },
      { word: 'STRAIT', clue: 'Narrow navigable waterway joining two seas' },
      { word: 'GULF', clue: 'Deep ocean inlet almost surrounded by coastline' },
      { word: 'HILL', clue: 'Naturally raised area of land below mountain height' },
      { word: 'PEAK', clue: 'Pointed apex summit of a mountain range' },
      { word: 'BAY', clue: 'Recessed coastal body of calm marine water' },
      { word: 'SEA', clue: 'Large body of saltwater smaller than an ocean' },
    ],
  },
  // 19: Science (8x8, 14 words)
  {
    level: 19,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 14,
    theme: 'Science',
    isMilestone: false,
    words: [
      { word: 'GRAVITY', clue: 'Universal force drawing masses toward one another' },
      { word: 'NUCLEUS', clue: 'Positively charged core of an atom containing protons' },
      { word: 'ELECTRON', clue: 'Subatomic particle possessing a negative electric charge' },
      { word: 'ENERGY', clue: 'Quantitative property transferred to perform work' },
      { word: 'GENOME', clue: 'Complete set of genetic genetic material in an organism' },
      { word: 'ORGAN', clue: 'Collection of differentiated tissues performing functions' },
      { word: 'CELL', clue: 'Basic structural and functional unit of biological life' },
      { word: 'ATOM', clue: 'Basic building block of ordinary chemical matter' },
      { word: 'FORCE', clue: 'Push or pull causing mass acceleration' },
      { word: 'LIGHT', clue: 'Electromagnetic radiation visible to human eye' },
      { word: 'HEAT', clue: 'Thermal energy transferred between bodies' },
      { word: 'WAVE', clue: 'Oscillatory disturbance propagating through a medium' },
      { word: 'MASS', clue: 'Fundamental measure of amount of matter' },
      { word: 'GENE', clue: 'Sequence of DNA encoding a functional protein' },
      { word: 'ACID', clue: 'Chemical molecule donating hydrogen ions with pH below 7' },
      { word: 'BASE', clue: 'Substance neutralizing acids with pH above 7' },
      { word: 'ION', clue: 'Atom or molecule bearing a net electrical charge' },
      { word: 'RAY', clue: 'Beam of light or radiated energy particles' },
      { word: 'GAS', clue: 'State of matter expanding freely without fixed shape' },
    ],
  },
  // 20: History (8x8, 14 words, Milestone 4)
  {
    level: 20,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 14,
    theme: 'History',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 4 Reached!',
      badgeId: 'chronos_keeper',
      badgeName: 'Chronos Historian',
      badgeIcon: 'Scroll',
      bonusCoins: 125,
      description: 'Level 20 Mastered! The corridors of world history are open to you.',
    },
    words: [
      { word: 'EMPIRE', clue: 'Extensive sovereign realm governed by an emperor' },
      { word: 'DYNASTY', clue: 'Hereditary line of ruling monarchs of one family' },
      { word: 'CASTLE', clue: 'Fortified medieval feudal residence with battlements' },
      { word: 'KNIGHT', clue: 'Armored equestrian warrior serving a medieval lord' },
      { word: 'SHIELD', clue: 'Broad defensive armor held to deflect weapons' },
      { word: 'TREATY', clue: 'Formal written binding accord negotiated between states' },
      { word: 'SWORD', clue: 'Bladed combat weapon with hilt and steel blade' },
      { word: 'CROWN', clue: 'Jeweled ornamental headdress worn by royalty' },
      { word: 'REIGN', clue: 'Period during which a sovereign exercises authority' },
      { word: 'SIEGE', clue: 'Military blockade encircling a city to compel surrender' },
      { word: 'KING', clue: 'Male hereditary sovereign ruler of an independent nation' },
      { word: 'MONK', clue: 'Religious ascetic living in seclusion within a monastery' },
      { word: 'HELM', clue: 'Protective metal headgear worn into combat' },
      { word: 'WAR', clue: 'Armed armed conflict conducted between sovereign states' },
      { word: 'ERA', clue: 'Distinct historical epoch distinguished by notable events' },
      { word: 'AGE', clue: 'Long historical division such as Bronze or Stone' },
      { word: 'BOW', clue: 'Tensioned ranged weapon propelling feathered arrows' },
    ],
  },
  // 21: Literature (8x8, 15 words)
  {
    level: 21,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 15,
    theme: 'Literature',
    isMilestone: false,
    words: [
      { word: 'TRAGEDY', clue: 'Dramatic play dealing with somber downfall of hero' },
      { word: 'SONNET', clue: 'Poetic verse form composed of 14 rhymed lines' },
      { word: 'STANZA', clue: 'Group of poetic verses forming a recurrent metrical unit' },
      { word: 'MEMOIR', clue: 'Autobiographical narrative of personal experiences' },
      { word: 'RHYME', clue: 'Correspondence of terminal sound between words' },
      { word: 'NOVEL', clue: 'Fictional prose narrative of book length' },
      { word: 'DRAMA', clue: 'Theatrical work portraying conflicting human passion' },
      { word: 'FABLE', clue: 'Short allegorical tale featuring animals imparting morals' },
      { word: 'METAPHOR', clue: 'Figure of speech applying term to non-literal context' },
      { word: 'POETRY', clue: 'Literary composition using aesthetic rhythm and verse' },
      { word: 'PLOT', clue: 'Sequential unfolding storyline of a literary narrative' },
      { word: 'TALE', clue: 'Fictitious or folkloric narrative recounting events' },
      { word: 'MYTH', clue: 'Traditional sacred story explaining early world origins' },
      { word: 'EPIC', clue: 'Lengthy poetic narrative recounting monumental heroic deeds' },
      { word: 'TEXT', clue: 'Original words of a written manuscript or printed work' },
      { word: 'BOOK', clue: 'Bound literary creation published for readers' },
      { word: 'PAGE', clue: 'One leaf of a printed volume or codex' },
      { word: 'PROSE', clue: 'Written language in ordinary grammatical structure' },
      { word: 'ODE', clue: 'Lyrical poem honoring and praising an inspiring subject' },
      { word: 'PEN', clue: 'Writer instrument crafting verses upon parchment' },
    ],
  },
  // 22: Music (8x8, 15 words)
  {
    level: 22,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 15,
    theme: 'Music',
    isMilestone: false,
    words: [
      { word: 'MELODY', clue: 'Tuneful sequence of notes pleasing to the ear' },
      { word: 'RHYTHM', clue: 'Regular patterned recurrence of beats and accents' },
      { word: 'CHORUS', clue: 'Refrain repeated after each verse of a song' },
      { word: 'TEMPO', clue: 'Pace or speed at which music passage is performed' },
      { word: 'GUITAR', clue: 'Fretted acoustic instrument with six plucked strings' },
      { word: 'VIOLIN', clue: 'High-pitched four-stringed wooden instrument played with bow' },
      { word: 'SONATA', clue: 'Classical instrumental composition in multiple movements' },
      { word: 'OPERA', clue: 'Grand theatrical production sung with full orchestra' },
      { word: 'CHORD', clue: 'Simultaneous sounding of three or more harmonious pitches' },
      { word: 'PIANO', clue: 'Keyboard acoustic instrument striking felt hammers on wire' },
      { word: 'DRUM', clue: 'Percussion membrane instrument keeping the pulse' },
      { word: 'BASS', clue: 'Lowest register of musical frequency or voice' },
      { word: 'SONG', clue: 'Short musical composition arranged for human singing' },
      { word: 'BEAT', clue: 'Basic rhythmic unit of metric musical time' },
      { word: 'TUNE', clue: 'Catchy recognizable melody' },
      { word: 'NOTE', clue: 'Symbol indicating musical pitch and duration' },
      { word: 'REST', clue: 'Interval of silence between musical notes' },
      { word: 'JAZZ', clue: 'American musical genre celebrated for syncopated swing' },
      { word: 'SOLO', clue: 'Musical passage executed by an individual soloist' },
    ],
  },
  // 23: Movies & entertainment (8x8, 16 words)
  {
    level: 23,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 16,
    theme: 'Movies & entertainment',
    isMilestone: false,
    words: [
      { word: 'DIRECTOR', clue: 'Visionary who oversees the filming and acting on set' },
      { word: 'PRODUCER', clue: 'Executive financing and supervising film creation' },
      { word: 'ACTRESS', clue: 'Female artist performing dramatic roles on screen' },
      { word: 'CINEMA', clue: 'Theater where motion pictures are screened' },
      { word: 'SCREEN', clue: 'Large projection surface displaying film visuals' },
      { word: 'SCENE', clue: 'Continuous unit of dramatic action in a film' },
      { word: 'SCRIPT', clue: 'Written manuscript of dialogue and stage directions' },
      { word: 'CAMERA', clue: 'Optical apparatus recording cinematic sequences' },
      { word: 'ACTION', clue: 'Director call initiating the filming of a scene' },
      { word: 'DRAMA', clue: 'Emotionally intense narrative genre' },
      { word: 'OSCAR', clue: 'Coveted Academy Award statuette' },
      { word: 'CAST', clue: 'Collective ensemble of actors appearing in a film' },
      { word: 'SHOT', clue: 'Single uninterrupted camera recording take' },
      { word: 'FILM', clue: 'Motion picture or celluloid strip' },
      { word: 'STAR', clue: 'Celebrated headlining marquee performer' },
      { word: 'PLOT', clue: 'Story progression and conflict in a movie' },
      { word: 'EDIT', clue: 'Assemble and trim video cuts into final sequence' },
      { word: 'ROLE', clue: 'Fictional character enacted by an actor' },
      { word: 'SET', clue: 'Constructed backdrop environment for filming' },
    ],
  },
  // 24: Human qualities (8x8, 16 words)
  {
    level: 24,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 16,
    theme: 'Human qualities',
    isMilestone: false,
    words: [
      { word: 'COURAGE', clue: 'Bravery in confronting fear, pain, or adversity' },
      { word: 'HONESTY', clue: 'Quality of being truthful, sincere, and upright' },
      { word: 'LOYALTY', clue: 'Faithful allegiance to friends, family, or cause' },
      { word: 'EMPATHY', clue: 'Capacity to understand and share feelings of others' },
      { word: 'WISDOM', clue: 'Deep understanding paired with sensible sound judgment' },
      { word: 'KINDNESS', clue: 'Benevolent and considerate disposition toward others' },
      { word: 'VALOR', clue: 'Heroic courage displayed in the face of peril' },
      { word: 'GRACE', clue: 'Elegance of demeanor and forgiving kindness' },
      { word: 'PRIDE', clue: 'Satisfaction derived from one accomplishments' },
      { word: 'HOPE', clue: 'Optimistic expectation of positive future outcomes' },
      { word: 'LOVE', clue: 'Profound affection and warm emotional devotion' },
      { word: 'ZEAL', clue: 'Fervent passion and enthusiasm for a cause' },
      { word: 'CALM', clue: 'Tranquil state undisturbed by agitation' },
      { word: 'WIT', clue: 'Inventive cleverness and quick humorous intellect' },
      { word: 'WARM', clue: 'Welcoming friendly and caring temperament' },
      { word: 'BOLD', clue: 'Showing intrepid willingness to take brave risks' },
      { word: 'TRUE', clue: 'Faithful and genuine without falsehood' },
      { word: 'PURE', clue: 'Free of corrupting moral blemish' },
    ],
  },
  // 25: Mixed vocabulary (8x8, 17 words, Milestone 5)
  {
    level: 25,
    difficulty: '⭐⭐⭐',
    tier: 'intermediate',
    gridSize: 8,
    wordCount: 17,
    theme: 'Mixed vocabulary',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 5 Reached!',
      badgeId: 'grand_lexicographer',
      badgeName: 'Grand Lexicographer',
      badgeIcon: 'BookOpen',
      bonusCoins: 150,
      description: 'Halfway to the summit! 25 levels conquered with brilliant vocabulary mastery.',
    },
    words: [
      { word: 'VIBRANT', clue: 'Full of dynamic energy, brightness, and vitality' },
      { word: 'HARMONY', clue: 'Pleasing arrangement of parts forming a unified whole' },
      { word: 'MYSTERY', clue: 'Enigma that baffles understanding or defies solution' },
      { word: 'SILENCE', clue: 'Complete absence of audible sound or disturbance' },
      { word: 'CRYSTAL', clue: 'Homogeneous solid with geometrically arranged atoms' },
      { word: 'SHADOW', clue: 'Dark outline cast by an opaque object blocking light' },
      { word: 'JOURNEY', clue: 'Expedition venturing toward a distant horizon' },
      { word: 'MIRROR', clue: 'Reflective glass surface showing one own visage' },
      { word: 'RIVER', clue: 'Natural freshwater stream wending toward the ocean' },
      { word: 'STONE', clue: 'Hard compact natural mineral matter' },
      { word: 'SPARK', clue: 'Glowing fiery particle emitted from blazing flame' },
      { word: 'FLAME', clue: 'Visible gaseous burning part of a fire' },
      { word: 'CLOUD', clue: 'Floating sky vapor drifting with the currents' },
      { word: 'WIND', clue: 'Atmospheric currents sweeping across hills' },
      { word: 'LIGHT', clue: 'Radiant illumination banishing darkness' },
      { word: 'TREE', clue: 'Perennial arboreal plant with wood trunk' },
      { word: 'GOLD', clue: 'Noble yellow metal highly prized in coinage' },
      { word: 'STAR', clue: 'Distant celestial nuclear furnace shining bright' },
      { word: 'SUN', clue: 'Daylight orb energizing terrestrial life' },
      { word: 'SEA', clue: 'Vast expanse of salt water covering earth' },
      { word: 'SKY', clue: 'Atmospheric vault visible above' },
      { word: 'ICE', clue: 'Frozen water formed in winter chill' },
      { word: 'RAY', clue: 'Narrow beam of radiant light' },
      { word: 'MOON', clue: 'Silvery night satellite orbiting earth' },
      { word: 'WAVE', clue: 'Oscillating swell of surface water' },
      { word: 'SAND', clue: 'Fine granular quartz along beaches' },
      { word: 'LEAF', clue: 'Green foliage catching solar photons' },
      { word: 'SEED', clue: 'Embryonic plant ready to sprout' },
      { word: 'ROOT', clue: 'Underground anchor drinking groundwater' },
      { word: 'ROAD', clue: 'Paved trail connecting distant cities' },
      { word: 'DOOR', clue: 'Hinged entrance welcoming travelers' },
      { word: 'BOOK', clue: 'Bound pages of wisdom and narratives' },
    ],
  },
];
