import { RawTheme } from './wordbanks';

export const themes26to40: RawTheme[] = [
  // 26: Advanced nature (9x9, 17 words)
  {
    level: 26,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 17,
    theme: 'Advanced nature',
    isMilestone: false,
    words: [
      { word: 'ECOSYSTEM', clue: 'Biological community of interacting organisms and habitat' },
      { word: 'BIOSPHERE', clue: 'Global sum of all terrestrial and aquatic ecosystems' },
      { word: 'SYMBIOSIS', clue: 'Intimate mutualistic association between distinct species' },
      { word: 'POLLINATOR', clue: 'Animal such as a bee transferring pollen to stigmas' },
      { word: 'DECIDUOUS', clue: 'Trees shedding leaves annually at the approach of winter' },
      { word: 'ESTUARY', clue: 'Tidal mouth of a large river where tide meets stream' },
      { word: 'SAVANNA', clue: 'Grassy tropical plain with scattered solitary trees' },
      { word: 'LICHEN', clue: 'Composite organism arising from algae and fungi' },
      { word: 'CANOPY', clue: 'High continuous overhead roof formed by tree crowns' },
      { word: 'BIOME', clue: 'Major regional ecological community type like tundra' },
      { word: 'FLORA', clue: 'Indigenous plant life characteristic of a region' },
      { word: 'FAUNA', clue: 'Animals native to a specific environment or time' },
      { word: 'MOSS', clue: 'Small non-vascular flowerless green spore plant' },
      { word: 'FERN', clue: 'Vascular plant reproducing via frond-borne spores' },
      { word: 'SOIL', clue: 'Top layer of earth supporting organic vegetation' },
      { word: 'SEED', clue: 'Embryonic plant enclosed in a protective coat' },
      { word: 'ROOT', clue: 'Subterranean organ anchoring plants and taking water' },
      { word: 'LEAF', clue: 'Principal photosynthetic foliage of vegetation' },
      { word: 'TREE', clue: 'Arboreal pillar of woodlands and old-growth groves' },
    ],
  },
  // 27: Advanced science (9x9, 18 words)
  {
    level: 27,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 18,
    theme: 'Advanced science',
    isMilestone: false,
    words: [
      { word: 'CATALYST', clue: 'Substance accelerating reaction rate without being consumed' },
      { word: 'ISOTOPE', clue: 'Variant form of element with differing neutron counts' },
      { word: 'QUANTUM', clue: 'Discrete minimum packet of electromagnetic energy' },
      { word: 'ENTROPY', clue: 'Thermodynamic measure of molecular disorder and chaos' },
      { word: 'SYNTHESIS', clue: 'Production of complex compounds from simple reagents' },
      { word: 'MUTATION', clue: 'Alteration in genetic nucleotide sequence of genome' },
      { word: 'PHOTON', clue: 'Elementary particle serving as the quantum of light' },
      { word: 'ENZYME', clue: 'Biological macromolecule acting as organic catalyst' },
      { word: 'PLASMA', clue: 'Ionized gaseous state composed of free ions and electrons' },
      { word: 'PROTON', clue: 'Subatomic particle possessing unit positive charge' },
      { word: 'NEUTRON', clue: 'Subatomic hadron carrying zero net electric charge' },
      { word: 'VALENCE', clue: 'Combining power of an atom with hydrogen or other atoms' },
      { word: 'ORBIT', clue: 'Curved gravitational trajectory around a massive body' },
      { word: 'LASER', clue: 'Device generating coherent monochromatic radiation' },
      { word: 'ATOM', clue: 'Smallest constituent unit of ordinary matter' },
      { word: 'ION', clue: 'Charged molecular or atomic species' },
      { word: 'ACID', clue: 'Proton donor having low pH' },
      { word: 'BASE', clue: 'Proton acceptor having high pH' },
      { word: 'RAY', clue: 'Narrow beam of electromagnetic emissions' },
      { word: 'GENE', clue: 'Hereditary unit consisting of DNA locus' },
    ],
  },
  // 28: World geography (9x9, 18 words)
  {
    level: 28,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 18,
    theme: 'World geography',
    isMilestone: false,
    words: [
      { word: 'EQUATOR', clue: 'Imaginary planetary line equidistant from the poles' },
      { word: 'MERIDIAN', clue: 'Line of longitude passing through prime Greenwich' },
      { word: 'PENINSULA', clue: 'Landmass projecting into water almost surrounded' },
      { word: 'ARCHIPELAGO', clue: 'Extensive group or chain of clustered islands' },
      { word: 'HEMISPHERE', clue: 'Half of the terrestrial celestial terrestrial sphere' },
      { word: 'ALTITUDE', clue: 'Vertical height of elevation above mean sea level' },
      { word: 'TROPICS', clue: 'Warm geographical zone bounded by Cancer and Capricorn' },
      { word: 'TUNDRA', clue: 'Vast, treeless, permanently sub-frozen Arctic plain' },
      { word: 'STEPPE', clue: 'Semi-arid, grass-covered temperate vast plain' },
      { word: 'CANYON', clue: 'Deep cleft between cliffs resulting from weathering' },
      { word: 'GULF', clue: 'Deep ocean inlet almost enclosed by curving coast' },
      { word: 'FJORD', clue: 'Steep-sided glacial inlet formed by marine flooding' },
      { word: 'DELTA', clue: 'Triangular alluvial silt deposit at river mouth' },
      { word: 'RIDGE', clue: 'Long narrow hilltop or chain of mountain crests' },
      { word: 'PEAK', clue: 'Highest summit point of an alpine massif' },
      { word: 'CAPE', clue: 'Pointed coastal promontory jutting into sea' },
      { word: 'ATTOLL', clue: 'Ring-shaped coral reef encircling a lagoon' },
      { word: 'SEA', clue: 'Expansive salt ocean basin' },
      { word: 'BAY', clue: 'Broad recessed inlet of the ocean' },
    ],
  },
  // 29: Ancient history (9x9, 19 words)
  {
    level: 29,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 19,
    theme: 'Ancient history',
    isMilestone: false,
    words: [
      { word: 'PHARAOH', clue: 'Ancient sovereign ruler of the dynastic Nile kingdom' },
      { word: 'PYRAMID', clue: 'Monumental stone tomb with triangular sloped faces' },
      { word: 'PAPYRUS', clue: 'Reedy aquatic plant processed into early writing paper' },
      { word: 'COLOSSEUM', clue: 'Monumental amphitheater where Roman gladiators fought' },
      { word: 'GLADIATOR', clue: 'Trained combatant fighting for public entertainment' },
      { word: 'CHARIOT', clue: 'Two-wheeled horse-drawn cart used in ancient warfare' },
      { word: 'SENATE', clue: 'Supreme governing council of the Roman Republic' },
      { word: 'SPARTA', clue: 'Militaristic ancient Greek city-state on Eurotas' },
      { word: 'ATHENS', clue: 'Birthplace of civic democracy and classic philosophy' },
      { word: 'LEGION', clue: 'Principal military unit of Roman heavy infantry' },
      { word: 'ORACLE', clue: 'Priestess delivering divine prophecies at Delphi' },
      { word: 'TEMPLE', clue: 'Sacred edifice dedicated to worship of deities' },
      { word: 'TOMB', clue: 'Subterranean burial chamber holding royal remains' },
      { word: 'SCRIBE', clue: 'Learned copyist recording ancient clay tablets' },
      { word: 'COIN', clue: 'Minted metallic piece of authorized currency' },
      { word: 'VASE', clue: 'Amphora vessel decorated with mythological black figures' },
      { word: 'HELM', clue: 'Bronze crested headgear worn in battle' },
      { word: 'MYTH', clue: 'Sacred legend recounting the deeds of gods' },
      { word: 'AGE', clue: 'Historic era such as Bronze or Iron epochs' },
    ],
  },
  // 30: Space (9x9, 19 words, Milestone 6)
  {
    level: 30,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 19,
    theme: 'Space',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 6 Reached!',
      badgeId: 'cosmic_voyager',
      badgeName: 'Cosmic Voyager',
      badgeIcon: 'Rocket',
      bonusCoins: 200,
      description: 'Level 30 conquered! You reached the stars and unlocked the Cosmic Milestone.',
    },
    words: [
      { word: 'SUPERNOVA', clue: 'Colossal stellar explosion outshining entire galaxies' },
      { word: 'TELESCOPE', clue: 'Optical instrument revealing deep interstellar cosmos' },
      { word: 'GALAXY', clue: 'Gravitationally bound system of billions of stars' },
      { word: 'NEBULA', clue: 'Luminous interstellar cloud of cosmic dust and gas' },
      { word: 'PLANET', clue: 'Massive celestial body orbiting a central star' },
      { word: 'METEOR', clue: 'Streak of incandescent light from debris burning in air' },
      { word: 'ORBIT', clue: 'Elliptical gravitational path traversed by a satellite' },
      { word: 'COMET', clue: 'Icy solar wanderer exhibiting a glowing ion tail' },
      { word: 'COSMOS', clue: 'The entire universe seen as an orderly harmonious whole' },
      { word: 'CRATER', clue: 'Bowl-shaped depression left by high-velocity impact' },
      { word: 'SATURN', clue: 'Magnificent gas giant adorned with dazzling icy rings' },
      { word: 'JUPITER', clue: 'Largest solar planet sporting the colossal Great Red Spot' },
      { word: 'PULSAR', clue: 'Rapidly pulsating magnetized rotating neutron star' },
      { word: 'STAR', clue: 'Luminous plasma furnace powering planetary warmth' },
      { word: 'MOON', clue: 'Natural satellite orbiting planets with tidal force' },
      { word: 'SUN', clue: 'Our central G-type main-sequence solar anchor' },
      { word: 'VOID', clue: 'Vast desolate empty expanse between galactic filaments' },
      { word: 'RAY', clue: 'High-energy cosmic ray traversing vacuum' },
      { word: 'SKY', clue: 'Atmospheric dome opening out toward the infinite' },
    ],
  },
  // 31: Philosophy (9x9, 20 words)
  {
    level: 31,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 20,
    theme: 'Philosophy',
    isMilestone: false,
    words: [
      { word: 'EPISTEMOLOGY', clue: 'Philosophical branch investigating the nature of knowledge' },
      { word: 'ONTOLOGY', clue: 'Metaphysical study of existence, being, and reality' },
      { word: 'DIALECTIC', clue: 'Discourse between two opposing views establishing truth' },
      { word: 'ETHICS', clue: 'Moral principles that govern behavior and conduct' },
      { word: 'LOGIC', clue: 'Systematic study of valid deduction and inference' },
      { word: 'REASON', clue: 'Power of the mind to think, comprehend, and infer' },
      { word: 'TRUTH', clue: 'Conformity with factual reality and actuality' },
      { word: 'DOGMA', clue: 'Principle laid down by authority as incontrovertibly true' },
      { word: 'MORAL', clue: 'Distinction between right and wrong conduct' },
      { word: 'VALUE', clue: 'Regard that something is held to deserve; importance' },
      { word: 'VIRTUE', clue: 'Behavior showing high moral excellence and goodness' },
      { word: 'IDEAL', clue: 'Standard or conception of perfection or excellence' },
      { word: 'SOUL', clue: 'Spiritual or immaterial part of a human being' },
      { word: 'MIND', clue: 'Faculty of consciousness, thought, and volition' },
      { word: 'WILL', clue: 'Faculty by which a person decides upon action' },
      { word: 'SELF', clue: 'Essential being that distinguishes a person from others' },
      { word: 'GOOD', clue: 'That which is morally righteous and beneficial' },
      { word: 'FREE', clue: 'Acting of one own volition without coercion' },
      { word: 'REAL', clue: 'Actually existing as a thing or occurring in fact' },
      { word: 'ACT', clue: 'Conscious moral deed or exercise of volition' },
    ],
  },
  // 32: Arts (9x9, 20 words)
  {
    level: 32,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 9,
    wordCount: 20,
    theme: 'Arts',
    isMilestone: false,
    words: [
      { word: 'SCULPTURE', clue: 'Three-dimensional art carved from marble or stone' },
      { word: 'CANVAS', clue: 'Heavy woven fabric stretched across a frame for oils' },
      { word: 'PORTRAIT', clue: 'Artistic likeness representing a specific person' },
      { word: 'FRESCO', clue: 'Mural painting executed upon freshly laid wet lime plaster' },
      { word: 'GALLERY', clue: 'Exhibition hall displaying curated fine visual art' },
      { word: 'PALETTE', clue: 'Thin oval board upon which an artist mixes colors' },
      { word: 'MOSAIC', clue: 'Pattern produced by cementing small colored tiles' },
      { word: 'EASEL', clue: 'Upright wooden tripod frame supporting artist canvas' },
      { word: 'BRUSH', clue: 'Implement with fine bristles used to apply paint' },
      { word: 'SKETCH', clue: 'Preliminary rough drawing executed with pencil' },
      { word: 'MURAL', clue: 'Grand artwork painted directly upon a permanent wall' },
      { word: 'SHADE', clue: 'Comparative darkness caused by intercepting light' },
      { word: 'TONE', clue: 'Particular quality, pitch, or color shade in a scene' },
      { word: 'HUE', clue: 'Specific gradation of spectrum color like emerald' },
      { word: 'PIGMENT', clue: 'Natural substance giving color to paints and dyes' },
      { word: 'ART', clue: 'Creative visual expression communicating soul' },
      { word: 'OILS', clue: 'Painting medium using drying vegetable oils' },
      { word: 'INK', clue: 'Fluid pigment used for calligraphy and lithographs' },
      { word: 'CLAY', clue: 'Earthy ceramic medium molded into pottery forms' },
      { word: 'PEN', clue: 'Fine drawing instrument used in hatching' },
    ],
  },
  // 33: Advanced technology (10x10, 21 words)
  {
    level: 33,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 10,
    wordCount: 21,
    theme: 'Advanced technology',
    isMilestone: false,
    words: [
      { word: 'ALGORITHM', clue: 'Step-by-step mathematical procedure for solving problems' },
      { word: 'PROCESSOR', clue: 'Silicon CPU executing instructions and computing arithmetic' },
      { word: 'BANDWIDTH', clue: 'Maximum rate of data transfer across a digital path' },
      { word: 'FIREWALL', clue: 'Network security barrier monitoring incoming packets' },
      { word: 'DATABASE', clue: 'Organized structured collection of searchable records' },
      { word: 'HARDWARE', clue: 'Physical mechanical components of a computing rig' },
      { word: 'SOFTWARE', clue: 'Programs, scripts, and applications running on machines' },
      { word: 'COMPILER', clue: 'Tool translating source code into executable binary' },
      { word: 'FIRMWARE', clue: 'Permanent software programmed into read-only memory' },
      { word: 'ROBOTIC', clue: 'Concerning automated mechanical programmable agents' },
      { word: 'ENCRYPT', clue: 'Convert plaintext into cipher text for security' },
      { word: 'NETWORK', clue: 'Mesh of interconnected terminals and routing nodes' },
      { word: 'SERVER', clue: 'Remote machine handling web requests and files' },
      { word: 'ROUTER', clue: 'Device directing network traffic between IP subnets' },
      { word: 'CLOUD', clue: 'Global servers delivering hosted compute and storage' },
      { word: 'CHIP', clue: 'Integrated microcircuit wafer of etched silicon' },
      { word: 'CODE', clue: 'Symbolic instructions written by software engineers' },
      { word: 'DATA', clue: 'Binary units of information processed in memory' },
      { word: 'BYTE', clue: 'Digital unit of storage composed of eight bits' },
      { word: 'BIT', clue: 'Fundamental binary digit holding zero or one' },
      { word: 'APP', clue: 'Client software engineered for user utilities' },
    ],
  },
  // 34: Psychology (10x10, 21 words)
  {
    level: 34,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 10,
    wordCount: 21,
    theme: 'Psychology',
    isMilestone: false,
    words: [
      { word: 'COGNITION', clue: 'Mental action of acquiring knowledge and understanding' },
      { word: 'BEHAVIOR', clue: 'Observable manner in which one acts toward stimuli' },
      { word: 'EMOTION', clue: 'Complex psychological state involving physiological response' },
      { word: 'MEMORY', clue: 'Faculty by which mind stores and recalls information' },
      { word: 'STIMULUS', clue: 'Thing or event that evokes a specific functional reaction' },
      { word: 'NEURON', clue: 'Specialized cell transmitting electro-chemical nerve impulses' },
      { word: 'TRAUMA', clue: 'Deep emotional shock causing long-lasting psychological wound' },
      { word: 'HABIT', clue: 'Settled regular tendency or practice hard to give up' },
      { word: 'INSTINCT', clue: 'Innate, typically fixed pattern of unlearned behavior' },
      { word: 'ANXIETY', clue: 'Feeling of worry, nervousness, or unease about outcomes' },
      { word: 'PHOBIA', clue: 'Extreme or irrational fear of or aversion to something' },
      { word: 'DRIVE', clue: 'Innate psychological urge compelling purposeful action' },
      { word: 'MOOD', clue: 'Pervasive, sustained emotional state coloring perception' },
      { word: 'MIND', clue: 'Seat of consciousness, thought, intellect, and feelings' },
      { word: 'EGO', clue: 'Psychoanalytic mediator between primal id and superego' },
      { word: 'ID', clue: 'Freudian reservoir of instinctual unconscious impulses' },
      { word: 'ACT', clue: 'Voluntary expression of motivated physical behavior' },
      { word: 'FEAR', clue: 'Unpleasant emotion induced by perceived threat or danger' },
      { word: 'JOY', clue: 'Feeling of great happiness and deep emotional delight' },
      { word: 'RAGE', clue: 'Violent uncontrollable outburst of explosive anger' },
      { word: 'HOPE', clue: 'Optimistic mindset anticipating positive resolutions' },
    ],
  },
  // 35: Economics (10x10, 22 words, Milestone 7)
  {
    level: 35,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 10,
    wordCount: 22,
    theme: 'Economics',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 7 Reached!',
      badgeId: 'wealth_of_nations',
      badgeName: 'Wealth of Nations',
      badgeIcon: 'Coins',
      bonusCoins: 250,
      description: 'Level 35 complete! You deciphered market dynamics and fiscal equilibrium.',
    },
    words: [
      { word: 'INFLATION', clue: 'General progressive increase in consumer price index' },
      { word: 'MONOPOLY', clue: 'Exclusive possession or single control of a market' },
      { word: 'CAPITAL', clue: 'Wealth in the form of money or assets owned by business' },
      { word: 'DEFICIT', clue: 'Amount by which expenditure exceeds fiscal revenue' },
      { word: 'SURPLUS', clue: 'Excess of assets or budget remaining after demand' },
      { word: 'TARIFF', clue: 'Tax or duty imposed on imported foreign commodities' },
      { word: 'INTEREST', clue: 'Fee charged by lender to borrower for use of assets' },
      { word: 'ASSET', clue: 'Useful or valuable economic quality, person, or property' },
      { word: 'MARKET', clue: 'Regular gathering of buyers and sellers for commerce' },
      { word: 'SUPPLY', clue: 'Total amount of a specific good available to consumers' },
      { word: 'DEMAND', clue: 'Consumer desire to purchase goods and willingness to pay' },
      { word: 'TRADE', clue: 'Action of buying, selling, or bartering merchandise' },
      { word: 'PROFIT', clue: 'Financial gain difference between amount earned and spent' },
      { word: 'CREDIT', clue: 'Contractual agreement granting borrower instant funds' },
      { word: 'DEBT', clue: 'Something owed or due, typically money to a creditor' },
      { word: 'BOND', clue: 'Fixed-income instrument representing a corporate loan' },
      { word: 'STOCK', clue: 'Securities representing fractional ownership of a firm' },
      { word: 'COST', clue: 'Outlay of money required to purchase or manufacture' },
      { word: 'TAX', clue: 'Compulsory financial charge levied by government' },
      { word: 'FEE', clue: 'Payment made to a professional in exchange for advice' },
      { word: 'COIN', clue: 'Standardized circular metal currency piece' },
      { word: 'CASH', clue: 'Ready physical currency in coins and banknotes' },
    ],
  },
  // 36: Politics & society (10x10, 22 words)
  {
    level: 36,
    difficulty: '⭐⭐⭐⭐',
    tier: 'advanced',
    gridSize: 10,
    wordCount: 22,
    theme: 'Politics & society',
    isMilestone: false,
    words: [
      { word: 'DEMOCRACY', clue: 'System of governance where citizens exercise power' },
      { word: 'ELECTION', clue: 'Formal civic decision-making process selecting leaders' },
      { word: 'CITIZEN', clue: 'Legally recognized subject or national of a state' },
      { word: 'JUSTICE', clue: 'Fair, equitable, and impartial administration of law' },
      { word: 'CONGRESS', clue: 'National legislative assembly deliberating policy' },
      { word: 'SENATE', clue: 'Upper assembly of democratic representative legislature' },
      { word: 'CABINET', clue: 'Advisory council of high-ranking ministry executives' },
      { word: 'STATUTE', clue: 'Written law enacted by a legislative parliamentary body' },
      { word: 'RIGHTS', clue: 'Legal, social, or ethical principles of freedom' },
      { word: 'NATION', clue: 'Large body of people united by common descent or culture' },
      { word: 'POLICY', clue: 'Principle or course of action adopted by administration' },
      { word: 'TREATY', clue: 'Formal ratified agreement between sovereign countries' },
      { word: 'VOTE', clue: 'Formal expression of choice in ballot referendum' },
      { word: 'LAW', clue: 'System of binding rules enforced through institutions' },
      { word: 'POLL', clue: 'Canvassing of public opinion by questioning voters' },
      { word: 'DUTY', clue: 'Moral or legal civic obligation incumbent on citizen' },
      { word: 'PACT', clue: 'Formal diplomatic accord or treaty between parties' },
      { word: 'RULE', clue: 'Authoritative guide for conduct or action' },
      { word: 'BILL', clue: 'Draft of a proposed statutory law presented to senate' },
      { word: 'TAX', clue: 'Levy collecting public treasury revenue' },
      { word: 'COURT', clue: 'Judicial tribunal adjudicating legal controversies' },
      { word: 'WAR', clue: 'State of armed combat between state adversaries' },
    ],
  },
  // 37: Rare vocabulary (10x10, 23 words)
  {
    level: 37,
    difficulty: '⭐⭐⭐⭐⭐',
    tier: 'expert',
    gridSize: 10,
    wordCount: 23,
    theme: 'Rare vocabulary',
    isMilestone: false,
    words: [
      { word: 'EPHEMERAL', clue: 'Lasting for a very brief transitory moment; fleeting' },
      { word: 'LABYRINTH', clue: 'Complicated irregular network of winding passages' },
      { word: 'ZEPHYR', clue: 'Gentle, mild, pleasant westerly breeze' },
      { word: 'SERENDIPITY', clue: 'Fortunate occurrence of valuable discoveries by chance' },
      { word: 'PETRICHOR', clue: 'Earthy scent produced when fresh rain falls on dry soil' },
      { word: 'HALCYON', clue: 'Denoting a period of idyllic peace, calm, and joy' },
      { word: 'QUERULOUS', clue: 'Habitually whining and petulantly complaining' },
      { word: 'MELLIFLUOUS', clue: 'Sweet, musical, and pleasant sounding to hear' },
      { word: 'TACITURN', clue: 'Reserved, silent, and saying little in conversation' },
      { word: 'PANOPLY', clue: 'Impressive and magnificent array or splendid display' },
      { word: 'VERDANT', clue: 'Lush green with rich flourishing foliage' },
      { word: 'SAGACITY', clue: 'Acuteness of mental discernment and sound judgment' },
      { word: 'NEBULOUS', clue: 'Indistinct, vague, ill-defined, or cloudy' },
      { word: 'LUMINOUS', clue: 'Radiating shed light, bright, or glowing in dark' },
      { word: 'ZENITH', clue: 'Highest celestial point reached; apex of fortune' },
      { word: 'NADIR', clue: 'Lowest, most despairing point in fortunes of person' },
      { word: 'CHIMERA', clue: 'Illusion or fabrication of mind; mythical beast' },
      { word: 'AURA', clue: 'Distinctive intangible quality surrounding a person' },
      { word: 'IDYLL', clue: 'Picturesque idyllic rustic pastoral scene or tale' },
      { word: 'AEON', clue: 'Immeasurably long indeterminate period of time' },
      { word: 'RUNE', clue: 'Mysterious ancient letter having cryptic magical meaning' },
      { word: 'ECHO', clue: 'Reverberation of sound off a canyon wall' },
      { word: 'MIST', clue: 'Cloud of tiny water droplets suspended in atmosphere' },
    ],
  },
  // 38: Synonyms (10x10, 23 words)
  {
    level: 38,
    difficulty: '⭐⭐⭐⭐⭐',
    tier: 'expert',
    gridSize: 10,
    wordCount: 23,
    theme: 'Synonyms',
    isMilestone: false,
    words: [
      { word: 'ABUNDANT', clue: 'Existing in copious, lavish quantities; plentiful' },
      { word: 'GENEROUS', clue: 'Willing to give freely; magnanimous, unselfish' },
      { word: 'COURTEOUS', clue: 'Polite, respectful, and considerate in manner' },
      { word: 'DILIGENT', clue: 'Showing meticulous steady care in duties; assiduous' },
      { word: 'SPLENDID', clue: 'Magnificent, brilliant, superb, and dazzling' },
      { word: 'SERENE', clue: 'Calm, peaceful, tranquil, and untroubled' },
      { word: 'SINCERE', clue: 'Free from pretense or deceit; genuine, honest' },
      { word: 'TENACIOUS', clue: 'Holding fast firmly; persistent, resolute' },
      { word: 'SWIFT', clue: 'Moving with great rapidity; fleet, speedy, fast' },
      { word: 'BRAVE', clue: 'Ready to face danger; valiant, intrepid, bold' },
      { word: 'WISE', clue: 'Possessing sound judgment; sagacious, prudent' },
      { word: 'LUCID', clue: 'Expressed clearly; easily understood, transparent' },
      { word: 'KEEN', clue: 'Sharp, piercing, intellectually acute or eager' },
      { word: 'BOLD', clue: 'Daring, courageous, fearless, and adventurous' },
      { word: 'TRUE', clue: 'Faithful, authentic, honest, and verifiable' },
      { word: 'CALM', clue: 'Tranquil, placid, peaceful, unruffled' },
      { word: 'GLAD', clue: 'Feeling joy, delighted, pleased, and cheerful' },
      { word: 'RICH', clue: 'Affluent, wealthy, opulent, and prosperous' },
      { word: 'POOR', clue: 'Destitute, penniless, needy, and indigent' },
      { word: 'VAST', clue: 'Immense, colossal, boundless, and enormous' },
      { word: 'TINY', clue: 'Minute, minuscule, diminutive, and petite' },
      { word: 'FAIR', clue: 'Impartial, just, unbiased, and equitable' },
      { word: 'PURE', clue: 'Unadulterated, chaste, spotless, and pristine' },
    ],
  },
  // 39: Wordplay (10x10, 24 words)
  {
    level: 39,
    difficulty: '⭐⭐⭐⭐⭐',
    tier: 'expert',
    gridSize: 10,
    wordCount: 24,
    theme: 'Wordplay',
    isMilestone: false,
    words: [
      { word: 'ANAGRAM', clue: 'Word formed by rearranging letters of another word' },
      { word: 'PALINDROME', clue: 'Word reading the same backwards as forward like racecar' },
      { word: 'PUNSTER', clue: 'Clever humorist who frequently plays with double meanings' },
      { word: 'RIDDLE', clue: 'Question phrased enigmatically requiring ingenuity' },
      { word: 'CIPHER', clue: 'Secret cryptographic algorithm disguising meaning' },
      { word: 'ACROSTIC', clue: 'Poem where initial letters spell a hidden name' },
      { word: 'SPOONERISM', clue: 'Transposition of initial sounds in spoken phrase' },
      { word: 'CHARADE', clue: 'Game where syllables are acted out in pantomime' },
      { word: 'HOMOPHONE', clue: 'Word having identical pronunciation but different sense' },
      { word: 'ENIGMA', clue: 'Person or thing that is mysterious and puzzling' },
      { word: 'REBUS', clue: 'Puzzle in which words are represented by pictures' },
      { word: 'TWIST', clue: 'Unexpected clever turn in a story or phrase' },
      { word: 'CLUE', clue: 'Piece of evidence guiding solver toward solution' },
      { word: 'JEST', clue: 'Witty remark said in playful good-humored fun' },
      { word: 'QUIZ', clue: 'Test of mental wit and trivia knowledge' },
      { word: 'PUN', clue: 'Humorous exploitation of different word senses' },
      { word: 'WIT', clue: 'Mental sharpness and inventive verbal humor' },
      { word: 'GAG', clue: 'Comic joke or trick causing amusement' },
      { word: 'RHYME', clue: 'End-syllable acoustic matching pair' },
      { word: 'CODE', clue: 'Symbolic encrypted cipher script' },
      { word: 'CONUNDRUM', clue: 'Confusing, difficult, or insoluble question' },
      { word: 'PARADOX', clue: 'Self-contradictory statement revealing truth' },
      { word: 'IRONY', clue: 'Expression of meaning using language signifying opposite' },
      { word: 'SATIRE', clue: 'Use of irony, sarcasm, or ridicule to expose folly' },
    ],
  },
  // 40: Idioms (10x10, 24 words, Milestone 8)
  {
    level: 40,
    difficulty: '⭐⭐⭐⭐⭐',
    tier: 'expert',
    gridSize: 10,
    wordCount: 24,
    theme: 'Idioms',
    isMilestone: true,
    milestoneReward: {
      title: 'Milestone 8 Reached!',
      badgeId: 'silver_tongue',
      badgeName: 'Silver Tongue',
      badgeIcon: 'Sparkles',
      bonusCoins: 300,
      description: 'Level 40 reached! You have completely decoded figurative language and idioms.',
    },
    words: [
      { word: 'SILVER', clue: 'Every dark storm cloud has this gleaming lining' },
      { word: 'NEEDLE', clue: 'Item exceedingly difficult to spot in a haystack' },
      { word: 'BRIDGE', clue: 'Structure you cross only when you finally get to it' },
      { word: 'FEATHER', clue: 'Birds of this light plumage flock together' },
      { word: 'HORSE', clue: 'Do not put the cart before this equine pulling power' },
      { word: 'STONE', clue: 'Leave no one unturned in a thorough investigation' },
      { word: 'BULLET', clue: 'Bite this hard lead projectile to face painful duty' },
      { word: 'BREAD', clue: 'Best invention since this was first sliced' },
      { word: 'WATER', clue: 'Still depths of this run remarkably deep' },
      { word: 'CLOUD', clue: 'Float on nine of these when overjoyed' },
      { word: 'APPLE', clue: 'This fruit does not fall far from the ancestral tree' },
      { word: 'CAKE', clue: 'You cannot both possess this dessert and consume it' },
      { word: 'BARK', clue: 'Canine vocalization that is often worse than bite' },
      { word: 'BITE', clue: 'Do not do this to the feeding hand that nourishes' },
      { word: 'ROPE', clue: 'At the very bitter end of this tangled lifeline' },
      { word: 'BOAT', clue: 'Do not rock this floating vessel unnecessarily' },
      { word: 'BOOK', clue: 'Never judge this bound volume by its cover alone' },
      { word: 'IRON', clue: 'Strike this metal alloy while it remains incandescent' },
      { word: 'ICE', clue: 'Break this frosty barrier to warm up a conversation' },
      { word: 'CAT', clue: 'Feline let out of the covert burlap bag' },
      { word: 'HAY', clue: 'Make this agricultural fodder while the sun shines' },
      { word: 'NUT', clue: 'Tough problem described as hard to crack' },
      { word: 'EGG', clue: 'Do not put all of these fragile orbs in one basket' },
      { word: 'PIE', clue: 'Easy as this sweet baked dessert' },
    ],
  },
];
