import { LevelData } from '../types';

export const levels41to50: LevelData[] = [
  {
    "level": 41,
    "difficulty": "⭐⭐⭐⭐⭐",
    "tier": "expert",
    "gridSize": 11,
    "theme": "Difficult mixed",
    "wordCount": 14,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Harmonic set of pitches sounding in unison",
        "answer": "CHORD",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "across",
        "clue": "Combination of musical notes simultaneously sounded",
        "answer": "HARMONY",
        "row": 1,
        "col": 0
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Lowest celestial point directly below observer",
        "answer": "NADIR",
        "row": 1,
        "col": 5
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Band of colors produced by separation of light",
        "answer": "SPECTRUM",
        "row": 1,
        "col": 8
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Repetition of acoustic wave reflected off canyon surface",
        "answer": "ECHO",
        "row": 1,
        "col": 10
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Heroic monumental saga celebrated across generations",
        "answer": "EPIC",
        "row": 2,
        "col": 7
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Complete empty spatial expanse lacking matter",
        "answer": "VOID",
        "row": 3,
        "col": 2
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Intricate network of winding, confounding passageways",
        "answer": "LABYRINTH",
        "row": 5,
        "col": 1
      },
      {
        "number": 9,
        "direction": "down",
        "clue": "Distinctive atmosphere generated by a personality",
        "answer": "AURA",
        "row": 5,
        "col": 2
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Thin fabric concealing something mysterious",
        "answer": "VEIL",
        "row": 6,
        "col": 10
      },
      {
        "number": 11,
        "direction": "across",
        "clue": "Transparent optical element with flat polished surfaces",
        "answer": "PRISM",
        "row": 7,
        "col": 1
      },
      {
        "number": 12,
        "direction": "down",
        "clue": "Profoundly wise scholar respected for great learning",
        "answer": "SAGE",
        "row": 7,
        "col": 4
      },
      {
        "number": 13,
        "direction": "across",
        "clue": "Ancient cryptographic letter inscribed upon stones",
        "answer": "RUNE",
        "row": 7,
        "col": 7
      },
      {
        "number": 14,
        "direction": "across",
        "clue": "Highest celestial point directly overhead",
        "answer": "ZENITH",
        "row": 10,
        "col": 3
      }
    ]
  },
  {
    "level": 42,
    "difficulty": "⭐⭐⭐⭐⭐",
    "tier": "expert",
    "gridSize": 11,
    "theme": "Abstract concepts",
    "wordCount": 13,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Concept of something without any limit or bounds",
        "answer": "INFINITY",
        "row": 0,
        "col": 3
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Continuous indefinite progress of events in sequence",
        "answer": "TIME",
        "row": 0,
        "col": 9
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Essential nature or ultimate reality of existence",
        "answer": "BEING",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Power to act, speak, or think without hindrance",
        "answer": "FREEDOM",
        "row": 2,
        "col": 3
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Development of events outside a person control",
        "answer": "FATE",
        "row": 2,
        "col": 3
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Cosmic thermodynamic decay toward maximum disorder",
        "answer": "ENTROPY",
        "row": 2,
        "col": 6
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Thought or mental concept conceived in intellect",
        "answer": "IDEA",
        "row": 3,
        "col": 0
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Property of being in accord with factual reality",
        "answer": "TRUTH",
        "row": 4,
        "col": 3
      },
      {
        "number": 8,
        "direction": "down",
        "clue": "Seemingly absurd statement that proves fundamentally true",
        "answer": "PARADOX",
        "row": 4,
        "col": 10
      },
      {
        "number": 9,
        "direction": "across",
        "clue": "Arrangement or disposition of things in harmonious relation",
        "answer": "ORDER",
        "row": 6,
        "col": 6
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Faculty of mental cognition and consciousness",
        "answer": "MIND",
        "row": 7,
        "col": 4
      },
      {
        "number": 11,
        "direction": "across",
        "clue": "Hidden power believed to control future events; fate",
        "answer": "DESTINY",
        "row": 8,
        "col": 0
      },
      {
        "number": 12,
        "direction": "across",
        "clue": "Quality of having experience and sound discernment",
        "answer": "WISDOM",
        "row": 10,
        "col": 1
      }
    ]
  },
  {
    "level": 43,
    "difficulty": "⭐⭐⭐⭐⭐",
    "tier": "expert",
    "gridSize": 11,
    "theme": "Advanced vocabulary",
    "wordCount": 11,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Never to be broken, infringed, or dishonored",
        "answer": "INVIOLABLE",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Enthusiasm or passion burning within the heart",
        "answer": "ARDOR",
        "row": 0,
        "col": 7
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Possessing or showing courage or determination",
        "answer": "VALIANT",
        "row": 2,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Shedding light; bright, radiant, and shining in dark",
        "answer": "LUMINOUS",
        "row": 2,
        "col": 2
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Intense and passionate feeling and dedication",
        "answer": "FERVOR",
        "row": 2,
        "col": 4
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Ability to make good judgments and quick decisions",
        "answer": "ACUMEN",
        "row": 3,
        "col": 0
      },
      {
        "number": 7,
        "direction": "down",
        "clue": "Having or showing great energy or enthusiasm",
        "answer": "ZEALOUS",
        "row": 3,
        "col": 10
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Feeling of deep satisfaction from achievements",
        "answer": "PRIDE",
        "row": 4,
        "col": 6
      },
      {
        "number": 9,
        "direction": "down",
        "clue": "Smoothness and elegance of movement or demeanor",
        "answer": "GRACE",
        "row": 6,
        "col": 6
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Effort, energy, or enthusiasm physically displayed",
        "answer": "VIGOR",
        "row": 6,
        "col": 8
      },
      {
        "number": 11,
        "direction": "across",
        "clue": "Having or showing keen mental discernment; shrewd",
        "answer": "SAGACIOUS",
        "row": 9,
        "col": 2
      }
    ]
  },
  {
    "level": 44,
    "difficulty": "⭐⭐⭐⭐⭐",
    "tier": "expert",
    "gridSize": 11,
    "theme": "Tricky clues",
    "wordCount": 14,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Face that never smiles despite having two moving hands",
        "answer": "CLOCK",
        "row": 0,
        "col": 0
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "Toothed implement that grooms but never bites",
        "answer": "COMB",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Metal notched tooth that never chews food",
        "answer": "KEY",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Land with cities but no houses, mountains but no trees",
        "answer": "MAP",
        "row": 2,
        "col": 6
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Case packed with ivory keys that opens no doors",
        "answer": "PIANO",
        "row": 2,
        "col": 8
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Piece of furniture that has four legs but never walks",
        "answer": "BED",
        "row": 2,
        "col": 10
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Object with a spine that possesses neither ribs nor bones",
        "answer": "BOOK",
        "row": 3,
        "col": 0
      },
      {
        "number": 7,
        "direction": "down",
        "clue": "Vegetable that makes you weep without causing grief",
        "answer": "ONION",
        "row": 3,
        "col": 2
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Cold solid crystal that floats upon its own melted self",
        "answer": "ICE",
        "row": 3,
        "col": 8
      },
      {
        "number": 9,
        "direction": "down",
        "clue": "Slender sewing tool with an eye that cannot see",
        "answer": "NEEDLE",
        "row": 4,
        "col": 4
      },
      {
        "number": 10,
        "direction": "across",
        "clue": "Vault that holds plenty of liquid currency",
        "answer": "RIVERBANK",
        "row": 5,
        "col": 1
      },
      {
        "number": 11,
        "direction": "down",
        "clue": "Knot worn on hair or weapon bent without breaking",
        "answer": "BOW",
        "row": 5,
        "col": 6
      },
      {
        "number": 12,
        "direction": "across",
        "clue": "Hand blade that blows breeze without breathing",
        "answer": "FAN",
        "row": 7,
        "col": 0
      },
      {
        "number": 13,
        "direction": "across",
        "clue": "Weapon said to strike mightier than any warrior sword",
        "answer": "PEN",
        "row": 9,
        "col": 3
      }
    ]
  },
  {
    "level": 45,
    "difficulty": "⭐⭐⭐⭐⭐",
    "tier": "expert",
    "gridSize": 11,
    "theme": "Expert mixed",
    "wordCount": 14,
    "isMilestone": true,
    "milestoneReward": {
      "title": "Milestone 9 Reached!",
      "badgeId": "polymath_virtuoso",
      "badgeName": "Polymath Virtuoso",
      "badgeIcon": "Brain",
      "bonusCoins": 400,
      "description": "Level 45 conquered! You stand at the threshold of the endgame master tier."
    },
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Elaborate musical composition for full orchestra",
        "answer": "SYMPHONY",
        "row": 0,
        "col": 2
      },
      {
        "number": 1,
        "direction": "down",
        "clue": "Stellar furnace guiding nocturnal navigation",
        "answer": "STAR",
        "row": 0,
        "col": 2
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Composition in metrical verse sparking emotion",
        "answer": "POEM",
        "row": 0,
        "col": 5
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Golden sovereign sustaining all terrestrial vitality",
        "answer": "SUN",
        "row": 2,
        "col": 9
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Geometric crystal dispersing white beam into spectrum",
        "answer": "PRISM",
        "row": 3,
        "col": 1
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Clairvoyant gazing through veil of tomorrow",
        "answer": "SEER",
        "row": 3,
        "col": 4
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "Wise thinker consulted by kings across centuries",
        "answer": "SAGE",
        "row": 4,
        "col": 0
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Silvery luminary controlling oceanic tides",
        "answer": "MOON",
        "row": 4,
        "col": 6
      },
      {
        "number": 7,
        "direction": "down",
        "clue": "Sacred timeless parable explaining natural forces",
        "answer": "MYTH",
        "row": 4,
        "col": 6
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Medieval forerunner of chemistry seeking philosopher stone",
        "answer": "ALCHEMY",
        "row": 5,
        "col": 0
      },
      {
        "number": 9,
        "direction": "across",
        "clue": "Recital of wondrous folklore adventures",
        "answer": "TALE",
        "row": 6,
        "col": 6
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Body of traditional knowledge passed down orally",
        "answer": "LORE",
        "row": 6,
        "col": 8
      },
      {
        "number": 11,
        "direction": "across",
        "clue": "Grandiose generational chronicle of legendary valor",
        "answer": "EPIC",
        "row": 7,
        "col": 0
      },
      {
        "number": 12,
        "direction": "across",
        "clue": "Original model or typical example of a character type",
        "answer": "ARCHETYPE",
        "row": 9,
        "col": 0
      }
    ]
  },
  {
    "level": 46,
    "difficulty": "🔥",
    "tier": "master",
    "gridSize": 12,
    "theme": "Very difficult",
    "wordCount": 13,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Focal intersection of intersecting pathways",
        "answer": "NEXUS",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Use of ambiguous language to conceal the actual truth",
        "answer": "EQUIVOCATION",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Unflinching bravery in face of mortal danger",
        "answer": "VALOR",
        "row": 0,
        "col": 8
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Admirably purposeful, determined, and unwavering",
        "answer": "RESOLUTE",
        "row": 2,
        "col": 0
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Eternal immaterial core of human individuality",
        "answer": "SOUL",
        "row": 2,
        "col": 5
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Quality of possessing acute mental discernment",
        "answer": "SAGACITY",
        "row": 2,
        "col": 5
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Perplexing puzzle defying easy rational solution",
        "answer": "ENIGMA",
        "row": 3,
        "col": 0
      },
      {
        "number": 7,
        "direction": "down",
        "clue": "Brought back into active consciousness from memory",
        "answer": "RECALLED",
        "row": 3,
        "col": 11
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Divine unmerited favor or poise of movement",
        "answer": "GRACE",
        "row": 4,
        "col": 7
      },
      {
        "number": 9,
        "direction": "across",
        "clue": "Veracity corresponding with factual actuality",
        "answer": "TRUTH",
        "row": 8,
        "col": 2
      },
      {
        "number": 10,
        "direction": "across",
        "clue": "Passionate devotion toward noble objective",
        "answer": "ZEAL",
        "row": 8,
        "col": 8
      },
      {
        "number": 11,
        "direction": "across",
        "clue": "Conscious intellectual faculty generating ideas",
        "answer": "MIND",
        "row": 10,
        "col": 8
      },
      {
        "number": 12,
        "direction": "across",
        "clue": "Adherence to what is morally right and noble",
        "answer": "HONOR",
        "row": 11,
        "col": 0
      }
    ]
  },
  {
    "level": 47,
    "difficulty": "🔥",
    "tier": "master",
    "gridSize": 12,
    "theme": "Expert vocabulary",
    "wordCount": 13,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Sprightly mental agility in verbal repartee",
        "answer": "WIT",
        "row": 0,
        "col": 5
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Exceeding what is sufficient or necessary; extra",
        "answer": "SUPERFLUOUS",
        "row": 0,
        "col": 7
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Having keen mental discernment and sound judgment",
        "answer": "SAGACIOUS",
        "row": 1,
        "col": 0
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Showing bold courage in the face of hazard",
        "answer": "AUDACIOUS",
        "row": 1,
        "col": 3
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Unwavering and steadfast in fidelity",
        "answer": "TRUE",
        "row": 2,
        "col": 11
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "Daring to venture into perilous unknowns",
        "answer": "BOLD",
        "row": 3,
        "col": 0
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "Gentle, light westerly springtime wind",
        "answer": "ZEPHYR",
        "row": 3,
        "col": 6
      },
      {
        "number": 8,
        "direction": "down",
        "clue": "Using very few words in speech; concise, terse",
        "answer": "LACONIC",
        "row": 4,
        "col": 5
      },
      {
        "number": 9,
        "direction": "down",
        "clue": "Having high moral qualities and ideals",
        "answer": "NOBLE",
        "row": 5,
        "col": 1
      },
      {
        "number": 10,
        "direction": "across",
        "clue": "Serene temperament unmoved by turmoil",
        "answer": "CALM",
        "row": 6,
        "col": 5
      },
      {
        "number": 11,
        "direction": "down",
        "clue": "Free from contaminating moral blemish",
        "answer": "PURE",
        "row": 8,
        "col": 9
      },
      {
        "number": 12,
        "direction": "across",
        "clue": "Clearly expressed and easily understood; lucid",
        "answer": "PERSPICUOUS",
        "row": 9,
        "col": 0
      },
      {
        "number": 13,
        "direction": "across",
        "clue": "Sharply perceptive and intellectually alert",
        "answer": "KEEN",
        "row": 11,
        "col": 8
      }
    ]
  },
  {
    "level": 48,
    "difficulty": "🔥",
    "tier": "master",
    "gridSize": 12,
    "theme": "Cryptic-style clues",
    "wordCount": 16,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "Immortal passenger aboard the mortal vessel",
        "answer": "SOUL",
        "row": 1,
        "col": 4
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Mystic affection binding hearts across distances",
        "answer": "LOVE",
        "row": 1,
        "col": 7
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Azure vault arching over mountain heights",
        "answer": "SKY",
        "row": 2,
        "col": 10
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Blaze takes wing in nocturnal summer meadows",
        "answer": "FIREFLY",
        "row": 4,
        "col": 4
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Promethean gift consuming wood with crackling heat",
        "answer": "FIRE",
        "row": 4,
        "col": 4
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Heavenly tears blessing agricultural crop yields",
        "answer": "RAIN",
        "row": 4,
        "col": 6
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "Vaporous ghost shrouding city streets at night",
        "answer": "FOG",
        "row": 4,
        "col": 8
      },
      {
        "number": 7,
        "direction": "down",
        "clue": "Soil planetary sphere harboring organic life",
        "answer": "EARTH",
        "row": 6,
        "col": 2
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Salty cradle of prehistoric evolution",
        "answer": "SEA",
        "row": 7,
        "col": 0
      },
      {
        "number": 8,
        "direction": "down",
        "clue": "Golden furnace fueling planetary cycles",
        "answer": "SUN",
        "row": 7,
        "col": 0
      },
      {
        "number": 9,
        "direction": "across",
        "clue": "Unseen workshop crafting dreams and reasonings",
        "answer": "MIND",
        "row": 7,
        "col": 4
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Liquid arrested in diamond-hard stillness",
        "answer": "ICE",
        "row": 7,
        "col": 5
      },
      {
        "number": 11,
        "direction": "down",
        "clue": "Twilight veil preceding the nocturnal shroud",
        "answer": "DUSK",
        "row": 7,
        "col": 7
      },
      {
        "number": 12,
        "direction": "down",
        "clue": "Rose-fingered herald announcing daily resurrection",
        "answer": "DAWN",
        "row": 7,
        "col": 10
      },
      {
        "number": 13,
        "direction": "across",
        "clue": "Relentless thief stealing youth second by second",
        "answer": "TIME",
        "row": 9,
        "col": 2
      },
      {
        "number": 14,
        "direction": "across",
        "clue": "Frozen downy plumage coating alpine pines",
        "answer": "SNOW",
        "row": 9,
        "col": 7
      }
    ]
  },
  {
    "level": 49,
    "difficulty": "🔥🔥",
    "tier": "master",
    "gridSize": 13,
    "theme": "Master",
    "wordCount": 16,
    "isMilestone": false,
    "clues": [
      {
        "number": 1,
        "direction": "across",
        "clue": "State of mutual concord, tranquility, and harmony",
        "answer": "PEACE",
        "row": 0,
        "col": 1
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Mental or moral strength to venture, persevere, and withstand",
        "answer": "COURAGE",
        "row": 0,
        "col": 4
      },
      {
        "number": 3,
        "direction": "across",
        "clue": "Energy or dynamic power exerted upon physical bodies",
        "answer": "FORCE",
        "row": 0,
        "col": 7
      },
      {
        "number": 4,
        "direction": "down",
        "clue": "Arbitrary configuration of celestial stars forming mythic shape",
        "answer": "CONSTELLATION",
        "row": 0,
        "col": 10
      },
      {
        "number": 5,
        "direction": "down",
        "clue": "Rational investigation of the truths and principles of being",
        "answer": "PHILOSOPHY",
        "row": 1,
        "col": 6
      },
      {
        "number": 6,
        "direction": "across",
        "clue": "State of being in strict accord with reality and fact",
        "answer": "TRUTH",
        "row": 2,
        "col": 2
      },
      {
        "number": 7,
        "direction": "across",
        "clue": "High moral worth, noble reputation, and upright integrity",
        "answer": "HONOR",
        "row": 2,
        "col": 8
      },
      {
        "number": 8,
        "direction": "down",
        "clue": "Voyage undertaken by an organized team with definite purpose",
        "answer": "EXPEDITION",
        "row": 3,
        "col": 0
      },
      {
        "number": 9,
        "direction": "across",
        "clue": "Radiant energy illuminating the cosmic expanse",
        "answer": "LIGHT",
        "row": 4,
        "col": 6
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Exceptional intellectual or creative power and original faculty",
        "answer": "GENIUS",
        "row": 4,
        "col": 8
      },
      {
        "number": 11,
        "direction": "down",
        "clue": "Predetermined inevitable course of monumental future events",
        "answer": "DESTINY",
        "row": 5,
        "col": 2
      },
      {
        "number": 12,
        "direction": "down",
        "clue": "Pleasing concord of concurrent musical tones and themes",
        "answer": "HARMONY",
        "row": 5,
        "col": 12
      },
      {
        "number": 13,
        "direction": "across",
        "clue": "Central life-giving star of our planetary realm",
        "answer": "SUN",
        "row": 6,
        "col": 6
      },
      {
        "number": 14,
        "direction": "across",
        "clue": "Exultation resulting from victory or notable success",
        "answer": "TRIUMPH",
        "row": 9,
        "col": 0
      },
      {
        "number": 15,
        "direction": "down",
        "clue": "Crescent orb casting soft luminescence on oceans",
        "answer": "MOON",
        "row": 9,
        "col": 4
      },
      {
        "number": 16,
        "direction": "across",
        "clue": "High renown, praise, and honor won through notable deeds",
        "answer": "GLORY",
        "row": 11,
        "col": 8
      }
    ]
  },
  {
    "level": 50,
    "difficulty": "🔥🔥🔥",
    "tier": "master",
    "gridSize": 13,
    "theme": "Ultimate Crossword",
    "wordCount": 15,
    "isMilestone": true,
    "milestoneReward": {
      "title": "Grand Sovereign of Crosswords!",
      "badgeId": "grand_crossword_sovereign",
      "badgeName": "Grand Sovereign",
      "badgeIcon": "Crown",
      "bonusCoins": 1000,
      "description": "You completed all 50 levels of the Crossword Progression! Absolute Legend."
    },
    "clues": [
      {
        "number": 1,
        "direction": "down",
        "clue": "Consummate work of outstanding artistry, skill, or intellect",
        "answer": "MASTERPIECE",
        "row": 0,
        "col": 0
      },
      {
        "number": 2,
        "direction": "down",
        "clue": "Tranquility following the completion of great labors",
        "answer": "PEACE",
        "row": 0,
        "col": 2
      },
      {
        "number": 3,
        "direction": "down",
        "clue": "Superior to all others in quality, excellence, or skill",
        "answer": "UNSURPASSED",
        "row": 0,
        "col": 8
      },
      {
        "number": 4,
        "direction": "across",
        "clue": "Monarch reigning supreme atop the crossword realm",
        "answer": "KING",
        "row": 1,
        "col": 6
      },
      {
        "number": 5,
        "direction": "across",
        "clue": "Beacon of achievement shining across eternity",
        "answer": "STAR",
        "row": 2,
        "col": 0
      },
      {
        "number": 6,
        "direction": "down",
        "clue": "Overcoming of an opponent, challenge, or final puzzle",
        "answer": "VICTORY",
        "row": 3,
        "col": 10
      },
      {
        "number": 7,
        "direction": "down",
        "clue": "Dynamism driving human progress and ambition",
        "answer": "FORCE",
        "row": 4,
        "col": 4
      },
      {
        "number": 8,
        "direction": "across",
        "clue": "Courageous conduct and qualities of a celebrated hero",
        "answer": "HEROISM",
        "row": 4,
        "col": 6
      },
      {
        "number": 8,
        "direction": "down",
        "clue": "Adherence to the highest ethical and intellectual codes",
        "answer": "HONOR",
        "row": 4,
        "col": 6
      },
      {
        "number": 9,
        "direction": "across",
        "clue": "Ability to do something or act in a particular manner",
        "answer": "POWER",
        "row": 6,
        "col": 0
      },
      {
        "number": 10,
        "direction": "down",
        "clue": "Quality of possessing deep knowledge and sound discernment",
        "answer": "WISDOM",
        "row": 6,
        "col": 2
      },
      {
        "number": 11,
        "direction": "down",
        "clue": "Epic long and eventful journey full of wondrous discoveries",
        "answer": "ODYSSEY",
        "row": 6,
        "col": 12
      },
      {
        "number": 12,
        "direction": "across",
        "clue": "Interlocking word puzzle invented by Arthur Wynne in 1913",
        "answer": "CROSSWORD",
        "row": 7,
        "col": 4
      },
      {
        "number": 13,
        "direction": "across",
        "clue": "Noble satisfaction in one supreme accomplishments",
        "answer": "PRIDE",
        "row": 10,
        "col": 5
      },
      {
        "number": 14,
        "direction": "across",
        "clue": "Magnificence, high renown, and veneration of triumph",
        "answer": "GLORY",
        "row": 12,
        "col": 8
      }
    ]
  }
];
